deploymentMode: SimpleScalable

loki:
  auth_enabled: false

  memberlist:
    service: loki-memberlist
    join_members:
      - loki-memberlist

  common:
    replication_factor: 2
    path_prefix: /var/loki
    ring:
      instance_addr: "${POD_IP}"
      kvstore:
        store: memberlist
    storage:
      s3:
        # Endpoint оставляем здесь
        endpoint: http://minio.minio.svc.cluster.local:9000
        bucketnames: loki-data
        region: us-east-1
        # Эти параметры важны для конфига, но мы продублируем их флагами для надежности
        s3forcepathstyle: true
        insecure: true

  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h

  storage:
    type: s3
    bucketNames:
      chunks: loki-data
      ruler: loki-data
      admin: loki-data
    s3:
      s3forcepathstyle: true

  compactor:
    working_directory: /var/loki/compactor
    compaction_interval: 10m
    retention_enabled: false
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    
  limits_config:
    retention_period: 30d

# --- КОМПОНЕНТЫ ---

write:
  replicas: 2
  persistence:
    enabled: true
    storageClass: managed-nfs-storage
    size: 10Gi
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: AWS_ACCESS_KEY_ID
      value: loki
    - name: AWS_SECRET_ACCESS_KEY
      value: FeerDe3o
    - name: AWS_REGION
      value: us-east-1
    - name: LOKI_COMMON_STORAGE_S3_S3FORCEPATHSTYLE
      value: "true"
    - name: LOKI_COMMON_STORAGE_S3_INSECURE
      value: "true"
    - name: LOKI_COMMON_STORAGE_S3_ENDPOINT
      value: http://minio.minio.svc.cluster.local:9000

read:
  replicas: 2
  persistence:
    enabled: true
    storageClass: managed-nfs-storage
    size: 10Gi
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: AWS_ACCESS_KEY_ID
      value: loki
    - name: AWS_SECRET_ACCESS_KEY
      value: FeerDe3o
    - name: AWS_REGION
      value: us-east-1
    - name: LOKI_COMMON_STORAGE_S3_S3FORCEPATHSTYLE
      value: "true"
    - name: LOKI_COMMON_STORAGE_S3_INSECURE
      value: "true"
    - name: LOKI_COMMON_STORAGE_S3_ENDPOINT
      value: http://minio.minio.svc.cluster.local:9000

backend:
  replicas: 2
  persistence:
    enabled: true
    storageClass: managed-nfs-storage
    size: 10Gi
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: AWS_ACCESS_KEY_ID
      value: loki
    - name: AWS_SECRET_ACCESS_KEY
      value: FeerDe3o
    - name: AWS_REGION
      value: us-east-1
    - name: LOKI_COMMON_STORAGE_S3_S3FORCEPATHSTYLE
      value: "true"
    - name: LOKI_COMMON_STORAGE_S3_INSECURE
      value: "true"
    - name: LOKI_COMMON_STORAGE_S3_ENDPOINT
      value: http://minio.minio.svc.cluster.local:9000

gateway:
  enabled: true
  replicas: 2

monitoring:
  selfMonitoring:
    enabled: false
    lokiCanary:
      enabled: false
  serviceMonitor:
    enabled: true
    metricsInstance:
      enabled: false 
    namespace: monitoring
    labels:
      release: kube-prometheus-stack
    interval: 15s
    scrapeTimeout: 10s
  prometheusRule:
    enabled: true
    labels:
      release: prometheus
    rules:
      - alert: LokiRequestErrors
        expr: 100 * sum(rate(loki_request_duration_seconds_count{status_code=~"5.."}[1m])) / sum(rate(loki_request_duration_seconds_count[1m])) > 10
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Loki is returning > 10% 5xx errors"      
test:
  enabled: false