deploymentMode: SimpleScalable

loki:
  auth_enabled: false
  memberlist:
    service: loki-memberlist
  common:
    replication_factor: 1
    path_prefix: /var/loki
    ring:
      instance_addr_type: ip  # Использовать IP пода вместо Hostname
      kvstore:
        store: memberlist 
    storage:
      s3:
        endpoint: http://minio.minio.svc.cluster.local:9000
        bucketnames: loki-data
        access_key_id: loki
        secret_access_key: FeerDe3o 
        s3forcepathstyle: true
        insecure: true

  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h

  storage:
    type: s3
    bucketNames:
      chunks: loki-data
      ruler: loki-data
      admin: loki-data

  compactor:
    working_directory: /var/loki/compactor
    delete_request_store: s3
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    
  limits_config:
    retention_period: 30d
  extraEnv:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
# --- КОМПОНЕНТЫ (Simple Scalable) ---

# 1. WRITE (Запись логов)
write:
  replicas: 1
  persistence:
    enabled: true
    storageClass: managed-nfs-storage
    size: 10Gi
  extraEnv:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
# 2. READ (Чтение/Поиск)
read:
  replicas: 1
  persistence:
    # Read-нодам нужен диск только для кэша, можно небольшой
    enabled: true
    storageClass: managed-nfs-storage
    size: 10Gi
  extraEnv:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
# 3. BACKEND (Компакция, управление)
backend:
  replicas: 2
  persistence:
    enabled: true
    storageClass: managed-nfs-storage
    size: 10Gi
  extraEnv:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
# 4. GATEWAY (Nginx - единая точка входа)
gateway:
  enabled: true
  replicas: 1


# Отключаем встроенный мониторинг, если у вас уже есть свой prometheus-stack
monitoring:
  selfMonitoring:
    enabled: false
    lokiCanary:
      enabled: false
  serviceMonitor:
    enabled: true
    metricsInstance:
      enabled: false # Не создавать новый инстанс Prometheus
    namespace: monitoring
    labels:
      release: kube-prometheus-stack
    interval: 15s
    scrapeTimeout: 10s
  prometheusRule:
    enabled: true
    labels:
      release: prometheus
    rules:
      - alert: LokiRequestErrors
        expr: 100 * sum(rate(loki_request_duration_seconds_count{status_code=~"5.."}[1m])) / sum(rate(loki_request_duration_seconds_count[1m])) > 10
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Loki is returning > 10% 5xx errors"      
test:
  enabled: false