config:
  clients:
    - url: http://loki-gateway.log.svc.cluster.local/loki/api/v1/push

# Настройки для корректного чтения логов контейнеров
snippets:
  pipelineStages:
    - cri: {}
    - docker: {}