apiVersion: v1
data:
  Corefile: ".:53 {\n    errors\n    health {\n       lameduck 5s\n    }\n    ready\n
    \   kubernetes cluster.local in-addr.arpa ip6.arpa {\n       pods insecure\n       fallthrough
    in-addr.arpa ip6.arpa\n       ttl 30\n    }\n    prometheus :9153\n    # Явно
    отправляем ccsfarm.local на BIND принудительно через TCP\n    forward ccsfarm.local
    10.10.1.151 {\n       force_tcp\n    }        \n    forward . /etc/resolv.conf\n
    \   cache 30\n    loop\n    reload\n    loadbalance\n}\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health {\n       lameduck 5s\n    }\n    ready\n    \n    # Kubernetes internal services\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n       pods insecure\n       fallthrough in-addr.arpa ip6.arpa\n       ttl 30\n    }\n    \n    # Prometheus metrics\n    prometheus :9153\n    \n    # Cache\n    cache 30\n    \n    # Forward ccsfarm.local to BIND\n    forward ccsfarm.local 10.10.1.151\n    \n    # Forward everything else to system resolver\n    forward . /etc/resolv.conf\n    \n    loop\n    reload\n    loadbalance\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"coredns","namespace":"kube-system"}}
  creationTimestamp: "2025-11-19T17:41:57Z"
  labels:
    k8slens-edit-resource-version: v1
  name: coredns
  namespace: kube-system
  resourceVersion: "44139562"
  uid: 6ab3e3fc-7dda-4dc1-9dd5-67cf088542ab
