postgresql:
  install: false

redis:
  install: false

installCertmanager: false

prometheus:
  install: false

nginx-ingress:
  enabled: false

#registry:
#  enabled: false

gitlab-runner:
  install: false

global:
  minio:
    enabled: false
  # Включаем Community Edition
  edition: ce

  initialRootPassword:
    key: password
    secret: initial-admin-password

  redis:
    auth:
      enabled: true
      secret: gitlab-redis
      key: redis-password
    host: redis.redis.svc.cluster.local
    namespace: redis
    port: 6379

  psql:
    host: postgres-np.postgres.svc.cluster.local
    namespace: postgres
    port: 5432
    database: gitlab
    username: sanches
    password:
      useSecret: true
      secret: postgres-secret
      key: POSTGRES_PASSWORD
    preparedStatements: false
    sslmode: disable

  ingress:
    configureCertmanager: false
    class: system-ingress
    provider: nginx
    #installCRDs: false 
    tls:
      enabled: false

  hosts:
    domain: ccsfarm.local
    https: false
    externalIP: 10.10.2.111

  appConfig:
    # https://docs.gitlab.com/charts/advanced/external-object-storage/#lfs-artifacts-uploads-packages-external-diffs-terraform-state-dependency-proxy
    lfs:
      bucket: gitlab-lfs-storage
      connection: # https://gitlab.com/gitlab-org/charts/gitlab/blob/master/doc/charts/globals.md#connection
        secret: minio-credentials
        key: connection
    artifacts:
      bucket: gitlab-artifacts-storage
      connection:
        secret: minio-credentials
        key: connection
    uploads:
      bucket: gitlab-uploads-storage
      connection:
        secret: minio-credentials
        key: connection
    packages:
      bucket: gitlab-packages-storage
      connection:
        secret: minio-credentials
        key: connection

    # https://docs.gitlab.com/charts/advanced/external-object-storage/#backups
    backups:
      bucket: gitlab-backup-storage
      tmpBucket: gitlab-tmp-storage

  ## https://docs.gitlab.com/charts/charts/globals#outgoing-email
  ## Outgoing email server settings
  smtp:
    enabled: true
    tls: false
    starttls_auto: false
    openssl_verify_mode: 'none'
    domain: "git.ccsfarm.local"
    address: mail-relay
    port: 25
    authentication: "none"
    password:
      secret: 'fake-mail-password'
      key: 'password'
  email:
    from: "noreply@gitlab.ccsfarm.local"
    display_name: "GitLab ccsfarm.local"

# https://docs.gitlab.com/charts/advanced/external-object-storage/#backups
gitlab:
  toolbox:
    backups:
      objectStorage:
        config:
          secret: s3-credentials
          key: config
  gitaly:
    persistence:
      size: 50Gi
      storageClass: "managed-nfs-storage"
