{{- if dig "objectStore" "kes" "configuration" false (.Values | merge (dict)) }}
apiVersion: v1
kind: Secret
metadata:
  name: kes-configuration
  namespace: {{ $.Values.namespaceOverride | default $.Release.Namespace | quote }}
  {{- if $.Values.annotations }}
  annotations:
    {{- $.Values.annotations | toYaml | nindent 4 }}
  {{- end }}
  {{- if $.Values.labels }}
  labels:
    {{- $.Values.labels | toYaml | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  server-config.yaml: |
    {{- .Values.objectStore.kes.configuration | nindent 4 }}
{{- end }}
