apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gitlab.mail-relay
  namespace: mail-relay
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      app: mail-relay
      ver: 0.0.1
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: sidekiq
            release: mail-relay
