---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: postgres  
  name: pgadmin-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "longhorn"
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: postgres  
  name: pgadmin
data:
  pgadmin-password: cGFzc3dvcmQ=
---
kind: Service
apiVersion: v1
metadata:
  namespace: postgres  
  name: pgadmin-svc
  labels:
    name: postgres-operator
spec:
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
      nodePort: 30861
  selector:
    app: pgadmin
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: postgres  
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      initContainers:
      - name: busibox
        image: busybox:1.34.1
        imagePullPolicy: IfNotPresent
        command:
          - 'sh'
          - '-c'
          - 'chown 5050:5050 /tmp/mount'
        volumeMounts:
          - mountPath: /tmp/mount
            name: state
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:9.10
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        env:
          - name: PGADMIN_CONFIG_SERVER_MODE
            value: "True"
          - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
            value: "False"
          - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
            value: "False" 
          - name: PGADMIN_DEFAULT_EMAIL
            value: "admin@email.com"
          - name: PGADMIN_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgadmin
                key: pgadmin-password
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.2"
          limits:
            memory: "800Mi"
            cpu: "0.8"
        volumeMounts:
          - mountPath: /var/lib/pgadmin
            name: state
      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: pgadmin-pvc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: postgres  
  name: pgadmin
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"  
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - pg.ccsfarm.local
    secretName: pgadmin-tls-secret   
  rules:
    - host: pg.ccsfarm.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pgadmin-svc
                port:
                  name: http
