apiVersion: v1
kind: Service
metadata:
  namespace: postgres  
  name: postgres-headless
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres-port
    targetPort: postgres-port
  clusterIP: None
  selector:
    app: postgres
    version: "16.0"
---
apiVersion: v1
kind: Service
metadata:
  namespace: postgres  
  name: postgres-np
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres-port
    targetPort: postgres-port
  type: ClusterIP
  selector:
    app: postgres
    version: "16.0"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: postgres  
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: sanches
  POSTGRES_PASSWORD: password
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: postgres  
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres 
      version: "16.0"
  serviceName: postgres-headless
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: postgres
        version: "16.0"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: postgres
          image: registry-nexus.ccsfarm.local/pg-ts-vector:latest
          imagePullPolicy: "IfNotPresent"
          args: ["-c", "shared_preload_libraries=timescaledb"]
          ports:
            - containerPort: 5432
              name: postgres-port
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
  volumeClaimTemplates:
  - metadata:
      name: postgresdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 10Gi 
 
