apiVersion: v1
kind: Service
metadata:
  namespace: postgres  
  name: postgres-headless
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres-port
    targetPort: postgres-port
  clusterIP: None
  selector:
    app: postgres
    version: "16.0"
---
apiVersion: v1
kind: Service
metadata:
  namespace: postgres  
  name: postgres-np
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres-port
    targetPort: postgres-port
  type: ClusterIP
  selector:
    app: postgres
    version: "16.0"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: postgres  
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: sanches
  POSTGRES_PASSWORD: password
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: postgres
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
      version: "16.0"
  serviceName: postgres-headless
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: postgres
        version: "16.0"
    spec:
      terminationGracePeriodSeconds: 30
      
      # --- ИСПРАВЛЕННЫЙ INIT CONTAINER ---
      initContainers:
      - name: init-permissions
        # Используем Т ТОТ ЖЕ образ, что и база. В нем точно есть юзер postgres.
        image: registry-nexus.ccsfarm.local/pg-ts-vector:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Preparing data directory..."
            # 1. Явно создаем подпапку (от рута это сработает)
            mkdir -p /var/lib/postgresql/data/pgdata
            
            # 2. Выставляем права (700 = только владелец может читать/писать)
            chmod 700 /var/lib/postgresql/data/pgdata
            
            # 3. Отдаем папку владельцу (в этом образе user 'postgres' существует)
            chown -R postgres:postgres /var/lib/postgresql/data
            
            echo "Permissions fixed."
        securityContext:
          runAsUser: 0 # Запускаем от рута, чтобы иметь право на chown
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdata

      containers:
        - name: postgres
          image: registry-nexus.ccsfarm.local/pg-ts-vector:latest
          imagePullPolicy: "IfNotPresent"
          args: ["-c", "shared_preload_libraries=timescaledb", "-c", "max_worker_processes=24", "-c", "timescaledb.max_background_workers=16"]
          ports:
            - containerPort: 5432
              name: postgres-port
          envFrom:
            - secretRef:
                name: postgres-secret
          
          # Указываем путь к той папке, которую создали в init-контейнере
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
              
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
  volumeClaimTemplates:
  - metadata:
      name: postgresdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 10Gi
